### ISSUE TITLE
I have a problem about opencv. looking forward your answer.

### ISSUE THREAD

**Issue by liqiyanaipython** [Horacehxw/Dynamic_ORB_SLAM2#2]
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.6) /home/pc/Dynamic_ORB_SLAM2-master/xiangguanku/opencv-3.4.6/modules/dnn/src/caffe/caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "ModelsCNN/frozen_inference_graph.pb" in function 'ReadProtoFromBinaryFile'

**Comment by Horacehxw** [comment]
have you set up the git-lfs and download the files in ModelsCNN directory successfully?

**Comment by liqiyanaipython** [comment]
Yes,I have.but I don't know where the error  happen.I just want to achieve executable file ,such as test,mask_rcnn, optflow ,and get the similar picture with you in Example package.Could you tell me how I run them? I'm very looking forward to your reply.very thank you!

**Comment by Horacehxw** [comment]
It's most probably a path issue. You have to either set the working directory to project home, or give the executable right relative path to ModelsCNN in command line arguments.
Take the tum_rgb for example, the correct command should be:
`./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml /path/to/dataset/rgbd_dataset_freiburg3_walking_xyz /path/to/associations/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_walking.txt ModelsCNN/  x` 
where x refers to the number of frames for each mask.

**Comment by liqiyanaipython** [comment]
oh! Very thank you! I think the dynamic_orb_slam is nice!
but I have  a  trouble about the executable file of mask_cnn.I want to run it ,but this is  wrong.could you tell me how I run the  executable file of mask_cnn in /Examples/MaskRCNN？ I look forward to hearing from you.
