### ISSUE TITLE
How to use it in TUM RGB-D datasets?

### ISSUE THREAD

**Issue by zhanghua7099** [Horacehxw/Dynamic_ORB_SLAM2#4]
Hi!
I download your code and compile it, but I can't get a good result in Tum dataset `rgbd_dataset_freiburg3_walking_xyz`. It may be that I use a wrong method.

`./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml /home/robot/datasets/rgbd_dataset_freiburg3_walking_xyz /home/robot/datasets/rgbd_dataset_freiburg3_walking_xyz/associations.txt ModelsCNN/`

Can you give me a command？
In another issues, you say that the correct command should be:
`./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml /path/to/dataset/rgbd_dataset_freiburg3_walking_xyz /path/to/associations/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_walking.txt ModelsCNN/ x`
where x refers to the number of frames for each mask.

Can you provide a specific `x` used in the experiment?

Thank you very much!

**Comment by Horacehxw** [comment]
I think your command is correct, may I see your results of running this?
For parameter x, x<5 will be suitable if you want a precise localization result, and defalut value is 1.

**Comment by zhanghua7099** [comment]
When I set x=1, It may have a error message:
`Can't open "ModelsCNN/frozen_inference_graph.pb" in function 'ReadProtoFromBinaryFile'`
If I don't set the value of x, I can run the program but I can just get the result of normal orb-slam2.
How to fix this problem?
Thank you!

**Comment by Horacehxw** [comment]
I see, in the first command, you didn't specify the target path, try this instead:
```
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml /home/robot/datasets/rgbd_dataset_freiburg3_walking_xyz /home/robot/datasets/rgbd_dataset_freiburg3_walking_xyz/associations.txt  results/w_xyz_walking.txt ModelsCNN/
```

If you still get the error message
```
Can't open "ModelsCNN/frozen_inference_graph.pb" in function 'ReadProtoFromBinaryFile'
```
check if you sucessfully downloaded the files in ModelsCNN, it should look like this

![image](https://user-images.githubusercontent.com/19310183/67821327-97abde00-faf7-11e9-9633-6ba8eb031d06.png)

If there're missing files, try to use git-lfs to pull the repo again.

**Comment by zhanghua7099** [comment]
This problem can be solved by using the command:
`./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml /home/robot/datasets/rgbd_dataset_freiburg3_walking_xyz /home/robot/datasets/rgbd_dataset_freiburg3_walking_xyz/associations.txt  results/w_xyz_walking.txt ModelsCNN/`
Thank you very much!
