### ISSUE TITLE
 [ WARN:0] DNN: OpenCL target is not supported with current OpenCL device (tested with Intel GPUs only), switching to CPU

### ISSUE THREAD

**Issue by 1171257311** [Horacehxw/Dynamic_ORB_SLAM2#5]
hello，when i run this programme,i got a warning:
 [ WARN:0] DNN: OpenCL target is not supported with current OpenCL device (tested with Intel GPUs only), switching to CPU.
meanwhile, it runs very slow.However ,my opencv is 3.4.3.Must i update my opencv to 3.4.5?

**Comment by Horacehxw** [comment]
This is a known issue for Dynamic_ORB_SLAM2. Currently OpenCL doesn't support nvidia GPU, so the mask-rcnn part may runs quite slowly. One option here is to set the "mask synchronization" parameter to be higher.

**Comment by 1171257311** [comment]
emmm,where to set the "mask synchronization" parameter?    :D
